export const GET_BASKET_SUCCESS="GET_BASKET_SUCCESS"
export const BASKET_REQUEST="BASKET_REQUEST"
export const BASKET_FAILURE="BASKET_FAILURE"
export const GET_BASKETS_INFO_SUCCESS = "GET_BASKETS_INFO_SUCCESS"
export const GET_SINGLE_BASKET_INFO_SUCCESS = 'GET_SINGLE_BASKET_INFO_SUCCESS'
export const GET_BASKETDATA_SUCCESS="GET_BASKETDATA_SUCCESS"
export const GET_NEW_INSTRUMENT_LIST_SUCCESS="GET_NEW_INSTRUMENT_LIST_SUCCESS"
export const GET_ORDER_HOLDINGS_SUCCESS="GET_ORDER_HOLDINGS_SUCCESS"


export const USER_LOADING = 'USER_LOADING';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_FORGOT_SUCCESS = 'USER_FORGOT_SUCCESS';
export const USER_RESET_SUCCESS = 'USER_RESET_SUCCESS';
export const USER_FAIL = 'USER_FAIL';
export const VALID_USER_LOGOUT_SUCCESS = 'VALID_USER_LOGOUT_SUCCESS';
export const USER_BALANCE_SUCCESS = "USER_BALANCE_SUCCESS";
